quarkus:
  openapi-generator:
    codegen:
      input-base-dir: ../core/src/main/resources/META-INF
      spec:
        openapi_yaml:
          config-key: rexclient
          import-mappings:
            Request: org.jboss.pnc.api.dto.Request
          base-package: org.jboss.pnc.rex.client
      exclude: openapi.json